services:
  db:
    image: postgres:16-alpine
    container_name: hortiflow_produtor_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hortiflow_produtor
      POSTGRES_PASSWORD: hortiflow_produtor
      POSTGRES_DB: hortiflow_produtor
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
